name: Deploy on Release

on:
  push:

jobs:
  tt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Release Name
        id: releasename
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/*/}
      - name: Tag Info
        run: |
          echo "_______________________________________________"
          echo "Event: ${{ github.event_name }}"
          echo "Version: ${{ steps.releasename.outputs.VERSION }}"
          echo "_______________________________________________"
      - name: set-version-tag-xcube-viewer
        uses: bc-org/gha-update-application-version-tags@main
        with:
          app: viewer
          phase: prod
          delimiter: ' '
          tag: latest
          hash: sha256-abcd
          working-directory: ./
          prefix: values-*
      - name: cat-result
        working-directory: ./
        run: |
          echo "----------------DEV-------------------"
          head values-*-dev.yaml
